# This is a basic workflow to help you get started with Actions

name: scraper

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 8 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ENV
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10.6'
      - run: pip install requests
      - name: Run python script
        run: python main.py
      - name: Commit
        run: |
          git config --global user.name "Pranav Vedasendur Senthilvel"
          git config --global user.email "pranavsenthil5@gmail.com"
          git add .
          git commit -am "Automated database dump"
          git push
      

   
